### ISSUE TITLE
[BUG] 0.0.1.6 下载报错

### ISSUE THREAD

**Issue by IllIIllIIIIlllI** [Johnserf-Seed/f2#127]
更新到了 0.0.1.6 下载报错

WARNING  您当前使用的版本 0.0.1.6 可能已过时，请考虑及时升级到最新版本 0.0.1.6，请使用 pip install -U f2 更新
INFO     应用：douyin
INFO     模式：post
INFO     主配置路径：C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml
INFO     自定义配置路径：D:\1software\TikTokDownload-1.5\my_apps.yaml

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Scripts\f2.exe\__main__.py", line 7, in <module>
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\apps\douyin\cli.py", line 441, in douyin
    ctx.invoke(set_cli_config, **kwargs)
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\cli\cli_commands.py", line 182, in set_cli_config
    asyncio.run(run_app(kwargs))
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\cli\cli_commands.py", line 189, in run_app
    app_module = importlib.import_module(f"f2.apps.{app_name}.handler")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\apps\douyin\handler.py", line 13, in <module>
    from f2.apps.douyin.crawler import DouyinCrawler, DouyinWebSocketCrawler
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\apps\douyin\crawler.py", line 13, in <module>
    from f2.apps.douyin.model import (
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\apps\douyin\model.py", line 11, in <module>
    class BaseRequestModel(BaseModel):
  File "C:\Users\YY\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\apps\douyin\model.py", line 28, in BaseRequestModel
    os_name: str = ClientConfManager.brm_os().get("name", "Windows")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

**Comment by Johnserf-Seed** [comment]
配置文件也需要用新版的，请纯净升级

**Comment by Johnserf-Seed** [comment]
然后代码从最新的https://github.com/Johnserf-Seed/f2/tree/v0.0.1.7-pw2 pull几个修复的提交

**Comment by IllIIllIIIIlllI** [comment]
配置文件更新了 f2也用0.0.1.7 还是同样的问题
![微信截图_20240708191523](https://github.com/Johnserf-Seed/f2/assets/129761473/613f41bc-0dfc-457b-8448-592560d226b4)

**Comment by Johnserf-Seed** [comment]
> 配置文件更新了 f2也用0.0.1.7 还是同样的问题 ![微信截图_20240708191523](https://private-user-images.githubusercontent.com/129761473/346538339-613f41bc-0dfc-457b-8448-592560d226b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mzc4NzcsIm5iZiI6MTcyMDQzNzU3NywicGF0aCI6Ii8xMjk3NjE0NzMvMzQ2NTM4MzM5LTYxM2Y0MWJjLTBkZmMtNDU3Yi04NDQ4LTU5MjU2MGQyMjZiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMTE5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmQ5NGFhNDYyYzczYTg1ODAyNjUwZTZiZDc1NGJjMTYwYmUwYTY5Nzc1ZTgzZjMxYTIyZmEwNzA5ZmI2ZTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.beYIrM3ps5nWUjB2XAN-amb6q_32-rdm1MNrLiywJA8)

是项目里的conf.yaml不是app.yaml

**Comment by IllIIllIIIIlllI** [comment]
> > 配置文件更新了 f2也用0.0.1.7 还是同样的问题 ![微信截图_20240708191523](https://private-user-images.githubusercontent.com/129761473/346538339-613f41bc-0dfc-457b-8448-592560d226b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mzc4NzcsIm5iZiI6MTcyMDQzNzU3NywicGF0aCI6Ii8xMjk3NjE0NzMvMzQ2NTM4MzM5LTYxM2Y0MWJjLTBkZmMtNDU3Yi04NDQ4LTU5MjU2MGQyMjZiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMTE5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmQ5NGFhNDYyYzczYTg1ODAyNjUwZTZiZDc1NGJjMTYwYmUwYTY5Nzc1ZTgzZjMxYTIyZmEwNzA5ZmI2ZTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.beYIrM3ps5nWUjB2XAN-amb6q_32-rdm1MNrLiywJA8)
> 
> 是项目里的conf.yaml不是app.yaml

![微信截图_20240708193538](https://github.com/Johnserf-Seed/f2/assets/129761473/e491d31a-facd-4876-a890-58c07e9bb34d)
这个版本对吗

**Comment by Johnserf-Seed** [comment]
> > > 配置文件更新了 f2也用0.0.1.7 还是同样的问题 ![微信截图_20240708191523](https://private-user-images.githubusercontent.com/129761473/346538339-613f41bc-0dfc-457b-8448-592560d226b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mzc4NzcsIm5iZiI6MTcyMDQzNzU3NywicGF0aCI6Ii8xMjk3NjE0NzMvMzQ2NTM4MzM5LTYxM2Y0MWJjLTBkZmMtNDU3Yi04NDQ4LTU5MjU2MGQyMjZiNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMTE5MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmQ5NGFhNDYyYzczYTg1ODAyNjUwZTZiZDc1NGJjMTYwYmUwYTY5Nzc1ZTgzZjMxYTIyZmEwNzA5ZmI2ZTUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.beYIrM3ps5nWUjB2XAN-amb6q_32-rdm1MNrLiywJA8)
> > 
> > 
> > 是项目里的conf.yaml不是app.yaml
> 
> ![微信截图_20240708193538](https://private-user-images.githubusercontent.com/129761473/346543259-e491d31a-facd-4876-a890-58c07e9bb34d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0Mzg5MjcsIm5iZiI6MTcyMDQzODYyNywicGF0aCI6Ii8xMjk3NjE0NzMvMzQ2NTQzMjU5LWU0OTFkMzFhLWZhY2QtNDg3Ni1hODkwLTU4YzA3ZTliYjM0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMTM3MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTY2N2M4YTQwMDA4ZjM4NGFiMmE5YmZkMTI4ZDQxMTA5ZmMzNWI3YWNmZjI5Y2RmYWZkYWEzNzI0ZGU4MGMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cvqlurbfhb9-OWkpLoyRctIYHNu1FcKQ49443v0V_2s) 这个版本对吗

是的，文档中的就是最新配置
https://johnserf-seed.github.io/f2/site-config.html#%E4%B8%BB%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by IllIIllIIIIlllI** [comment]
> Owner

还是同样报错

**Comment by IllIIllIIIIlllI** [comment]
> 如果配置成功是不会报conf.yaml里的错误的，所以你需要纯净安装

搞定了 感谢
