### ISSUE TITLE
[BUG] 命令行执行f2 dy下载报错：`sqlite3.OperationalError: table user_info_web has no column named nickname_raw`

### ISSUE THREAD

**Issue by Leo-Lee15** [Johnserf-Seed/f2#151]
- [x] 我查看了 [文档](https://johnserf-seed.github.io/f2/quick-start.html) 以及 [已关闭的问题](https://github.com/Johnserf-Seed/f2/issues?q=is%3Aissue+is%3Aclosed) 以寻找可能的解决方案。
- [x] 我在 [常见的问题与解决办法](https://johnserf-seed.github.io/f2/question-answer/qa.html) 中找不到我的问题。
- [x] ~~*你的问题是公开的，请注意删除个人敏感内容再上传*~~
- [x] 不按照模板填写的问题将不会得到优先的处理。

**详细描述错误**
命令行执行`f2 dy`报错，错误信息：
```
PS D:\tk> f2 dy
WARNING  您当前使用的版本 0.0.1.6 可能已过时，请考虑及时升级到最新版本 0.0.1.6，请使用 pip install -U f2 更新
INFO     应用：douyin
INFO     模式：post
INFO     主配置路径：C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml
INFO     自定义配置路径：C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Scripts\f2.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\apps\douyin\cli.py", line 441, in douyin
    ctx.invoke(set_cli_config, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\cli\cli_commands.py", line 182, in set_cli_config
    asyncio.run(run_app(kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\cli\cli_commands.py", line 190, in run_app
    await app_module.main(kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\apps\douyin\handler.py", line 1849, in main
    await mode_function_map[mode](DouyinHandler(kwargs))
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\apps\douyin\handler.py", line 251, in handle_user_post
    user_path = await self.get_or_add_user_data(self.kwargs, sec_user_id, udb)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\apps\douyin\handler.py", line 145, in get_or_add_user_data
    await db.add_user_info(**current_user_data._to_dict())
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\apps\douyin\db.py", line 74, in add_user_info
    await self.execute(
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\db\base_db.py", line 55, in execute
    await cursor.execute(query, parameters)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiosqlite\cursor.py", line 48, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiosqlite\cursor.py", line 40, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiosqlite\core.py", line 132, in _execute
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiosqlite\core.py", line 115, in run
    result = function()
             ^^^^^^^^^^
sqlite3.OperationalError: table user_info_web has no column named nickname_raw
```

**系统平台**
<details>
<summary>单击展开</summary>
Q:你在哪个平台（Win/Linux/Mac）上运行？你使用的是什么浏览器？你使用的是什么终端软件？你使用的F2是什么版本？

A: 

 - 操作系统: ` os Windows 11 x64 (build 22631); system   x86_64, mingw32`
 - 浏览器 [chrome 126.0.6478.127]
 - 终端 [WT 1.20.11781.0] 
 - F2版本 [0.0.1.6]

</details>

**错误重现**
<details>
<summary>单击展开</summary>
Q: 请你复制并粘贴出错时运行的命令和配置文件内容，以及重现该行为的步骤。如果你一次性就提供完整信息，就会节省很多解决问题的时间。

A: 
1. 命令行执行的命令：`f2 dy`
2. app.yml
```yml
douyin:
  cookie: MY_COOKIE
  lyric: true
  cover: true
  desc: yes
  folderize: true
  interval: all
  languages: zh_CN
  max_connections: 5
  max_counts: 0
  max_retries: 5
  max_tasks: 5
  music: true
  #naming: '{create}_{desc}'
  naming: '{create}_{aweme_id}'
  page_counts: 20
  mode: post
  path: ./Download
  timeout: 10
  url: https://www.douyin.com/user/MS4wLjABAAAAWxLpO0Q437qGFpnEKBIIaU5-xOj2yAhH3MNJi-AUY04
```

Q: 请添加调试命令`f2 -d DEBUG`重新运行出错的命令并提供日志目录下的日志文件。

A: 
```log
2024-07-21 12:16:17,097 - f2 - DEBUG - 调试模式：DEBUG
2024-07-21 12:16:17,719 - f2 - WARNING - 您当前使用的版本 0.0.1.6 可能已过时，请考虑及时升级到最新版本 0.0.1.6，请使用 pip install -U f2 更新
2024-07-21 12:16:17,880 - f2 - INFO - 应用：douyin
2024-07-21 12:16:17,900 - f2 - INFO - 模式：post
2024-07-21 12:16:17,900 - f2 - INFO - 主配置路径：C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml
2024-07-21 12:16:17,900 - f2 - INFO - 自定义配置路径：C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\f2\conf\app.yaml
2024-07-21 12:16:17,900 - f2 - DEBUG - 主配置参数：{'cookie': 'n_mh=***; LOGIN_STATUS=1; my_rd=2; passport_assist_user***; sso_uid_tt=***; sso_uid_tt_ss=***; toutiao_sso_user=***; toutiao_sso_user_ss=***; SEARCH_RESULT_LIST_TYPE=%22single%22; sid_ucp_sso_v1=1.0.0-***-***; ssid_ucp_sso_v1=1.0.0-***-***; passport_csrf_token=***; passport_csrf_token_default=***; d_ticket=***; _bd_ticket_crypt_doamin=2; __security_server_data_status=1; sessionid=***; sessionid_ss=***; sid_guard=***%***%***%***%***-Aug-2024+15%3A50%3A03+GMT; sid_tt=***; sid_ucp_v1=1.0.0-***; ssid_ucp_v1=1.0.0-***; uid_tt=***; uid_tt_ss=***; _bd_ticket_crypt_cookie=***; __live_version__=%221.1.2.1035%22; live_use_vvc=%22false%22; UIFID_TEMP=***; UIFID=***; WallpaperGuide=%7B%22showTime%22%***%2C%22closeTime%22%3A0%2C%22showCount%22%3A1%2C%22cursor1%22%3A7%2C%22cursor2%22%3A0%7D; publish_badge_show_info=%220%2C0%2C0%***%22; store-region=cn-sh; store-region-src=uid; strategyABtestKey=%221718937161.493%22; stream_player_status_params=%22%7B%5C%22is_auto_play%5C%22%3A1%2C%5C%22is_full_screen%5C%22%3A0%2C%5C%22is_full_webscreen%5C%22%3A0%2C%5C%22is_mute%5C%22%3A1%2C%5C%22is_speed%5C%22%3A1%2C%5C%22is_visible%5C%22%3A1%7D%22; volume_info=%7B%22isUserMute%22%3Afalse%2C%22isMute%22%3Atrue%2C%22volume%22%3A0.5%7D; FRIEND_NUMBER_RED_POINT_INFO=%***-***%2F1718985600000%2F1718983244687%2F0%2F0%22; FOLLOW_LIVE_POINT_INFO=%***-***%2F1718985600000%2F1718937158429%2F0%2F1718985296025%22; bd_ticket_guard_client_data=***%3D%3D; bd_ticket_guard_client_web_domain=2; stream_recommend_feed_params=%22%7B%5C%22cookie_enabled%5C%22%3Atrue%2C%5C%22screen_width%5C%22%3A1600%2C%5C%22screen_height%5C%22%3A1000%2C%5C%22browser_online%5C%22%3Atrue%2C%5C%22cpu_core_num%5C%22%3A20%2C%5C%22device_memory%5C%22%3A8%2C%5C%22downlink%5C%22%3A10%2C%5C%22effective_type%5C%22%3A%5C%224g%5C%22%2C%5C%22round_trip_time%5C%22%3A50%7D%22; FOLLOW_NUMBER_YELLOW_POINT_INFO=%***-***%2F1718985600000%2F1718984735319%2F1718984696025%2F0%22; pwa2=%220%7C0%7C3%7C1%22; home_can_add_dy_2_desktop=%221%22; odin_tt=***; ttwid=1%7CxlA6JH5l-***%7C1712164280%***; download_guide=%223%2F20240621%2F1%22; msToken=***; IsDouyinActive=false; xgplayer_user_id=***; __ac_signature=***-f71; xgplayer_device_id=***; s_v_web_id=***; fpk1=***++***/***==; fpk2=***; dy_sheight=1000; dy_swidth=1600; __ac_referer=__ac_blank; __ac_nonce=***', 'lyric': True, 'cover': True, 'desc': True, 'folderize': True, 'interval': 'all', 'languages': 'zh_CN', 'max_connections': 5, 'max_counts': 0, 'max_retries': 5, 'max_tasks': 5, 'music': True, 'naming': '{create}_{aweme_id}', 'page_counts': 20, 'mode': 'post', 'path': './Download', 'timeout': 10, 'url': 'https://www.douyin.com/user/***', 'proxies': {'http://': None, 'https://': None}}
2024-07-21 12:16:17,912 - f2 - DEBUG - 自定义配置参数：{'cookie': 'n_mh=***; LOGIN_STATUS=1; my_rd=2; passport_assist_user***; sso_uid_tt=***; sso_uid_tt_ss=***; toutiao_sso_user=***; toutiao_sso_user_ss=***; SEARCH_RESULT_LIST_TYPE=%22single%22; sid_ucp_sso_v1=1.0.0-***-***; ssid_ucp_sso_v1=1.0.0-***-***; passport_csrf_token=***; passport_csrf_token_default=***; d_ticket=***; _bd_ticket_crypt_doamin=2; __security_server_data_status=1; sessionid=***; sessionid_ss=***; sid_guard=***%***%***%***%***-Aug-2024+15%3A50%3A03+GMT; sid_tt=***; sid_ucp_v1=1.0.0-***; ssid_ucp_v1=1.0.0-***; uid_tt=***; uid_tt_ss=***; _bd_ticket_crypt_cookie=***; __live_version__=%221.1.2.1035%22; live_use_vvc=%22false%22; UIFID_TEMP=***; UIFID=***; WallpaperGuide=%7B%22showTime%22%***%2C%22closeTime%22%3A0%2C%22showCount%22%3A1%2C%22cursor1%22%3A7%2C%22cursor2%22%3A0%7D; publish_badge_show_info=%220%2C0%2C0%***%22; store-region=cn-sh; store-region-src=uid; strategyABtestKey=%221718937161.493%22; stream_player_status_params=%22%7B%5C%22is_auto_play%5C%22%3A1%2C%5C%22is_full_screen%5C%22%3A0%2C%5C%22is_full_webscreen%5C%22%3A0%2C%5C%22is_mute%5C%22%3A1%2C%5C%22is_speed%5C%22%3A1%2C%5C%22is_visible%5C%22%3A1%7D%22; volume_info=%7B%22isUserMute%22%3Afalse%2C%22isMute%22%3Atrue%2C%22volume%22%3A0.5%7D; FRIEND_NUMBER_RED_POINT_INFO=%***-***%2F1718985600000%2F1718983244687%2F0%2F0%22; FOLLOW_LIVE_POINT_INFO=%***-***%2F1718985600000%2F1718937158429%2F0%2F1718985296025%22; bd_ticket_guard_client_data=***%3D%3D; bd_ticket_guard_client_web_domain=2; stream_recommend_feed_params=%22%7B%5C%22cookie_enabled%5C%22%3Atrue%2C%5C%22screen_width%5C%22%3A1600%2C%5C%22screen_height%5C%22%3A1000%2C%5C%22browser_online%5C%22%3Atrue%2C%5C%22cpu_core_num%5C%22%3A20%2C%5C%22device_memory%5C%22%3A8%2C%5C%22downlink%5C%22%3A10%2C%5C%22effective_type%5C%22%3A%5C%224g%5C%22%2C%5C%22round_trip_time%5C%22%3A50%7D%22; FOLLOW_NUMBER_YELLOW_POINT_INFO=%***-***%2F1718985600000%2F1718984735319%2F1718984696025%2F0%22; pwa2=%220%7C0%7C3%7C1%22; home_can_add_dy_2_desktop=%221%22; odin_tt=***; ttwid=1%7CxlA6JH5l-***%7C1712164280%***; download_guide=%223%2F20240621%2F1%22; msToken=***; IsDouyinActive=false; xgplayer_user_id=***; __ac_signature=***-f71; xgplayer_device_id=***; s_v_web_id=***; fpk1=***++***/***==; fpk2=***; dy_sheight=1000; dy_swidth=1600; __ac_referer=__ac_blank; __ac_nonce=***', 'lyric': True, 'cover': True, 'desc': True, 'folderize': True, 'interval': 'all', 'languages': 'zh_CN', 'max_connections': 5, 'max_counts': 0, 'max_retries': 5, 'max_tasks': 5, 'music': True, 'naming': '{create}_{aweme_id}', 'page_counts': 20, 'mode': 'post', 'path': './Download', 'timeout': 10, 'url': 'https://www.douyin.com/user/***', 'proxies': {'http://': None, 'https://': None}}
2024-07-21 12:16:17,912 - f2 - DEBUG - CLI参数：{'cookie': 'n_mh=***; LOGIN_STATUS=1; my_rd=2; passport_assist_user***; sso_uid_tt=***; sso_uid_tt_ss=***; toutiao_sso_user=***; toutiao_sso_user_ss=***; SEARCH_RESULT_LIST_TYPE=%22single%22; sid_ucp_sso_v1=1.0.0-***-***; ssid_ucp_sso_v1=1.0.0-***-***; passport_csrf_token=***; passport_csrf_token_default=***; d_ticket=***; _bd_ticket_crypt_doamin=2; __security_server_data_status=1; sessionid=***; sessionid_ss=***; sid_guard=***%***%***%***%***-Aug-2024+15%3A50%3A03+GMT; sid_tt=***; sid_ucp_v1=1.0.0-***; ssid_ucp_v1=1.0.0-***; uid_tt=***; uid_tt_ss=***; _bd_ticket_crypt_cookie=***; __live_version__=%221.1.2.1035%22; live_use_vvc=%22false%22; UIFID_TEMP=***; UIFID=***; WallpaperGuide=%7B%22showTime%22%***%2C%22closeTime%22%3A0%2C%22showCount%22%3A1%2C%22cursor1%22%3A7%2C%22cursor2%22%3A0%7D; publish_badge_show_info=%220%2C0%2C0%***%22; store-region=cn-sh; store-region-src=uid; strategyABtestKey=%221718937161.493%22; stream_player_status_params=%22%7B%5C%22is_auto_play%5C%22%3A1%2C%5C%22is_full_screen%5C%22%3A0%2C%5C%22is_full_webscreen%5C%22%3A0%2C%5C%22is_mute%5C%22%3A1%2C%5C%22is_speed%5C%22%3A1%2C%5C%22is_visible%5C%22%3A1%7D%22; volume_info=%7B%22isUserMute%22%3Afalse%2C%22isMute%22%3Atrue%2C%22volume%22%3A0.5%7D; FRIEND_NUMBER_RED_POINT_INFO=%***-***%2F1718985600000%2F1718983244687%2F0%2F0%22; FOLLOW_LIVE_POINT_INFO=%***-***%2F1718985600000%2F1718937158429%2F0%2F1718985296025%22; bd_ticket_guard_client_data=***%3D%3D; bd_ticket_guard_client_web_domain=2; stream_recommend_feed_params=%22%7B%5C%22cookie_enabled%5C%22%3Atrue%2C%5C%22screen_width%5C%22%3A1600%2C%5C%22screen_height%5C%22%3A1000%2C%5C%22browser_online%5C%22%3Atrue%2C%5C%22cpu_core_num%5C%22%3A20%2C%5C%22device_memory%5C%22%3A8%2C%5C%22downlink%5C%22%3A10%2C%5C%22effective_type%5C%22%3A%5C%224g%5C%22%2C%5C%22round_trip_time%5C%22%3A50%7D%22; FOLLOW_NUMBER_YELLOW_POINT_INFO=%***-***%2F1718985600000%2F1718984735319%2F1718984696025%2F0%22; pwa2=%220%7C0%7C3%7C1%22; home_can_add_dy_2_desktop=%221%22; odin_tt=***; ttwid=1%7CxlA6JH5l-***%7C1712164280%***; download_guide=%223%2F20240621%2F1%22; msToken=***; IsDouyinActive=false; xgplayer_user_id=***; __ac_signature=***-f71; xgplayer_device_id=***; s_v_web_id=***; fpk1=***++***/***==; fpk2=***; dy_sheight=1000; dy_swidth=1600; __ac_referer=__ac_blank; __ac_nonce=***', 'lyric': True, 'cover': True, 'desc': True, 'folderize': True, 'interval': 'all', 'languages': 'zh_CN', 'max_connections': 5, 'max_counts': 0, 'max_retries': 5, 'max_tasks': 5, 'music': True, 'naming': '{create}_{aweme_id}', 'page_counts': 20, 'mode': 'post', 'path': './Download', 'timeout': 10, 'url': 'https://www.douyin.com/user/***', 'proxies': {'http://': None, 'https://': None}, 'auto_cookie': None, 'headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0', 'Referer': 'https://www.douyin.com/'}}
2024-07-21 12:16:18,069 - f2 - DEBUG - 生成真实的msToken
2024-07-21 12:16:18,228 - f2 - DEBUG - 生成真实的msToken
2024-07-21 12:16:18,450 - f2 - DEBUG - 用户信息接口地址：https://www.douyin.com/aweme/v1/web/user/profile/other/?device_platform=webapp&aid=6383&channel=channel_pc_web&pc_client_type=1&version_code=190500&version_name=19.5.0&cookie_enabled=true&screen_width=1920&screen_height=1080&browser_language=zh-CN&browser_platform=Win32&browser_name=Edge&browser_version=122.0.0.0&browser_online=true&engine_name=Blink&engine_version=122.0.0.0&os_name=Windows&os_version=10&cpu_core_num=12&device_memory=8&platform=PC&downlink=10&effective_type=4g&round_trip_time=100&msToken=***==&sec_user_id=***&a_bogus=***/***/***-XsAtl-***-zo0/9Vf=
2024-07-21 12:16:18,767 - f2 - DEBUG - 响应状态码: 200
```

</details>

**预期行为**
预期下载成功

**Comment by HentaiBoros** [comment]
我没有用过 dy，但从你的报错来看问题是由于没有在 sqlite 数据库中 user_info_web 表找到 nickname_raw 列导致的，检查你的依赖以及数据库和表是否被正常创建

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/user-attachments/assets/33f26f0d-84af-4fe6-a3d9-308631318d5f)

**Comment by zxxxz121212** [comment]
这个数据库文件在哪里删除。我报了同样的错误，使用的是最新版本，当时开了三个窗口进行并行下载douyin视频，但是只有其中一个窗口下载成功了，其他两个窗口虽然也没报错，但是并没有保存文件，我再次下载那两个douyin视频就报这个错误了：
![image](https://github.com/user-attachments/assets/71b52859-3403-4310-ade7-542c9d302a2c)

**Comment by Johnserf-Seed** [comment]
> 这个数据库文件在哪里删除。我报了同样的错误，使用的是最新版本，当时开了三个窗口进行并行下载douyin视频，但是只有其中一个窗口下载成功了，其他两个窗口虽然也没报错，但是并没有保存文件，我再次下载那两个douyin视频就报这个错误了： ![image](https://private-user-images.githubusercontent.com/108661394/387373929-71b52859-3403-4310-ade7-542c9d302a2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2NDUzNTcsIm5iZiI6MTczNTY0NTA1NywicGF0aCI6Ii8xMDg2NjEzOTQvMzg3MzczOTI5LTcxYjUyODU5LTM0MDMtNDMxMC1hZGU3LTU0MmM5ZDMwMmEyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMVQxMTM3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzJhMzMwYzk0YTljNjViNzc5NmMxZGE4OTE1MDBmYjJmYTE4ZDJlZDE3Y2QwNDVkNjc0MWZiZGZhOWZhODM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OFJClV4yNt3gsNhvUBc3b2bwnNHzwEh2T9eAHwiQiBY)

终端在哪个目录就在哪个目录下生成日志与数据库文件
