### ISSUE TITLE
[BUG]RuntimeError: There is no current event loop in thread 'MainThread'

### ISSUE THREAD

**Issue by OldPengTou** [Johnserf-Seed/f2#159]
- [x] 我查看了 [文档](https://johnserf-seed.github.io/f2/quick-start.html) 以及 [已关闭的问题](https://github.com/Johnserf-Seed/f2/issues?q=is%3Aissue+is%3Aclosed) 以寻找可能的解决方案。
- [x] 我在 [常见的问题与解决办法](https://johnserf-seed.github.io/f2/question-answer/qa.html) 中找不到我的问题。
- [ ] ~~*你的问题是公开的，请注意删除个人敏感内容再上传*~~
- [ ] 不按照模板填写的问题将不会得到优先的处理。

- 如果错误问题是可视化的，请在**屏幕截图**贴截图。如果你是开发者请在**错误重现**提供一个最小的代码示例来演示该问题。
- 相同的问题将会被标记`重复(duplicate)`，如果你的问题被标记为`已确认(confirmed)`则会在后续的推送中修复，请时刻留意。
- 退订邮件提醒请点击邮件的底部`unsubscribe`。

**详细描述错误**
简明扼要地描述遇到的错误。

**系统平台**
<details>
<summary>单击展开</summary>
Q:你在哪个平台（Win/Linux/Mac）上运行？你使用的是什么浏览器？你使用的是什么终端软件？你使用的F2是什么版本？

A: 

 - 操作系统: Win11
 - 浏览器 Chrome
 - 终端 [Windows Terminal](https://aka.ms/terminal)
 - F2版本 0.0.1.6

</details>

**错误重现**
<details>
<summary>单击展开</summary>
Q: 请你复制并粘贴出错时运行的命令和配置文件内容，以及重现该行为的步骤。如果你一次性就提供完整信息，就会节省很多解决问题的时间。

A: 

1. F:\Environment\Python\python-3.9.0-amd64\Lib\site-packages\f2\conf>f2 dy -c conf/dyshangjia0728.yaml
INFO     您当前使用的是最新版本：0.0.1.6
INFO     应用：douyin
INFO     模式：one
INFO     主配置路径：f:\environment\python\python-3.9.0-amd64\lib\site-packages\f2\conf\app.yaml
INFO     自定义配置路径：F:\Environment\Python\python-3.9.0-amd64\Lib\site-packages\f2\conf\conf\dyshangjia0728.yaml
Traceback (most recent call last):
  File "f:\environment\python\python-3.9.0-amd64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "f:\environment\python\python-3.9.0-amd64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\Environment\Python\python-3.9.0-amd64\Scripts\f2.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "f:\environment\python\python-3.9.0-amd64\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "f:\environment\python\python-3.9.0-amd64\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "f:\environment\python\python-3.9.0-amd64\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "f:\environment\python\python-3.9.0-amd64\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "f:\environment\python\python-3.9.0-amd64\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "f:\environment\python\python-3.9.0-amd64\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "f:\environment\python\python-3.9.0-amd64\lib\site-packages\f2\apps\douyin\cli.py", line 441, in douyin
    ctx.invoke(set_cli_config, **kwargs)
  File "f:\environment\python\python-3.9.0-amd64\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "f:\environment\python\python-3.9.0-amd64\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "f:\environment\python\python-3.9.0-amd64\lib\site-packages\f2\cli\cli_commands.py", line 178, in set_cli_config
    SignalManager().register_shutdown_signal()
  File "f:\environment\python\python-3.9.0-amd64\lib\site-packages\f2\utils\_singleton.py", line 21, in __call__
    instance = super().__call__(*args, **kwargs)
  File "f:\environment\python\python-3.9.0-amd64\lib\site-packages\f2\utils\_signal.py", line 11, in __init__
    self._shutdown_event = asyncio.Event()
  File "f:\environment\python\python-3.9.0-amd64\lib\asyncio\locks.py", line 177, in __init__
    self._loop = events.get_event_loop()
  File "f:\environment\python\python-3.9.0-amd64\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
2. 
3. 

Q: 请添加调试命令`f2 -d DEBUG`重新运行出错的命令并提供日志目录下的日志文件。

A: 

Q: 如果是开发者请提供最小的代码示例

A: 

```python

```

</details>

**预期行为**
简明扼要地描述期望发生的事情。

**屏幕截图**
请添加截图以帮助解释你的问题。

**日志文件**
请添加调试日志文件以帮助解释你的问题。

**其他**
如有，可以添加有关问题的其他信息。

**Comment by OnClickListener2048** [comment]
same here

**Comment by sasvageangelss1** [comment]
替换完之后 ImportError: cannot import name 'check_f2_version' from 'f2.utils.utils'

**Comment by lanybass** [comment]
依然报错

**Comment by lanybass** [comment]
我改回上一版的代码反而可以运行了：
把 get_command中的asyncio.run(check_version())改回：
> from concurrent.futures import ThreadPoolExecutor
>def run_async_in_thread(coro):
>    """在单独的线程中运行异步任务"""
>    loop = asyncio.new_event_loop()
>    asyncio.set_event_loop(loop)
>executor = ThreadPoolExecutor(max_workers=1)
> executor.submit(run_async_in_thread, check_version)

**Comment by ciring** [comment]
same 
安装的的0.0.1.7

╭────────────────────────────────────────────────────────────────────────────────── F2 版本检查 ──────────────────────────────────────────────────────────────────────────────────╮
│ 您当前使用的是最新版本：0.0.1.6                                                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
INFO     应用：douyin
INFO     模式：one
INFO     主配置路径：C:\Users\chenruisi\Documents\f2-0.0.1.7-pw2\f2-0.0.1.7-pw2\f2\conf\app.yaml
INFO     自定义配置路径：C:\Users\chenruisi\Documents\f2-0.0.1.7-pw2\f2-0.0.1.7-pw2\f2\conf\app.yaml
Traceback (most recent call last):
  File "C:\Users\chenruisi\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\chenruisi\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\chenruisi\AppData\Local\Programs\Python\Python39\Scripts\f2.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\chenruisi\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\chenruisi\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\chenruisi\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\chenruisi\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\chenruisi\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\chenruisi\AppData\Local\Programs\Python\Python39\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\chenruisi\Documents\f2-0.0.1.7-pw2\f2-0.0.1.7-pw2\f2\apps\douyin\cli.py", line 481, in douyin
    ctx.invoke(set_cli_config, **kwargs)
  File "C:\Users\chenruisi\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\chenruisi\AppData\Local\Programs\Python\Python39\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\chenruisi\Documents\f2-0.0.1.7-pw2\f2-0.0.1.7-pw2\f2\cli\cli_commands.py", line 172, in set_cli_config
    SignalManager().register_shutdown_signal()
  File "C:\Users\chenruisi\Documents\f2-0.0.1.7-pw2\f2-0.0.1.7-pw2\f2\utils\_singleton.py", line 21, in __call__
    instance = super().__call__(*args, **kwargs)
  File "C:\Users\chenruisi\Documents\f2-0.0.1.7-pw2\f2-0.0.1.7-pw2\f2\utils\_signal.py", line 11, in __init__
    self._shutdown_event = asyncio.Event()
  File "C:\Users\chenruisi\AppData\Local\Programs\Python\Python39\lib\asyncio\locks.py", line 177, in __init__
    self._loop = events.get_event_loop()
  File "C:\Users\chenruisi\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

**Comment by Johnserf-Seed** [comment]
python的版本不匹配会导致异步事件兼容性问题，推荐升级到 Python 3.10 或更高版本
