### ISSUE TITLE
[BUG] weibo模式特定情况下出错

### ISSUE THREAD

**Issue by LRTFK** [Johnserf-Seed/f2#223]
weibo，post模式
博主   url: https://weibo.com/u/1723261380
运行前一段时间都没有问题，知道一个2016年的微博，出错。报错日志片段在下面。

INFO     [  跳过  ]: 2016-06-15                                                                                                 
         15-37-00_红红火火恍恍惚惚____风吹丁丁响当当_卧槽___感觉好痛____然后下面就没了___吓人____关爱智障儿童成长_跟我做的小黄人
         有异曲同工之妙__......红红火火恍恍惚惚____风吹丁丁响当当_卧槽___感觉好痛____然后下面就没了___吓人____关爱智障儿童成长_ 
         跟我做的小黄人有异曲同工之妙___desc.txt
INFO     [  跳过  ]: 2016-06-15
         12-00-09_还在羡慕内部人员的秒杀_还是可以疯抢的大牌断色断码一口价_这个618再也不用眼馋人家的巨额折扣_十五号预热已经开始_ 
         衣恋618送你一场约_惠__旗下品牌2折起_明星同款买就送你_一折秒杀断......杀断码疯抢_http___t_cn_R56ubb7_http___t_cn_R5XKmZF
         _____http___mapi_0067XV5ujw1f4vrbis2l7j30m81l8dlm_desc.txt
↖ [  图片  ]:2016-06-16 09-29-26_...了________image_1.jpg ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0.0%  • 0/? bytes ? ETA        
↗ [  图片  ]:2016-06-16 09-29-26_...了________image_1.jpg ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  0.0% • 0/? bytes ? ETA      
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Temp\f2\.venv\Scripts\f2.exe\__main__.py", line 7, in <module>
  File "d:\Temp\f2\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Temp\f2\.venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "d:\Temp\f2\.venv\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Temp\f2\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Temp\f2\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Temp\f2\.venv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Temp\f2\f2\apps\weibo\cli.py", line 387, in weibo
    ctx.invoke(set_cli_config, **kwargs)
  File "d:\Temp\f2\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Temp\f2\.venv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Temp\f2\f2\cli\cli_commands.py", line 169, in set_cli_config
    asyncio.run(run_app(kwargs))
  File "C:\Users\zhangsan\scoop\apps\python311\current\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\zhangsan\scoop\apps\python311\current\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhangsan\scoop\apps\python311\current\Lib\asyncio\base_events.py", line 654, in run_until_co  File "C:\Users\zhangsan\scoop\apps\python311\current\Lib\asyncio\base_events.py", line 654, in run_until_complete
  File "C:\Users\zhangsan\scoop\apps\python311\current\Lib\asyncio\base_events.py", line 654, in run_until_complete
  File "C:\Users\zhangsan\scoop\apps\python311\current\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
  File "C:\Users\zhangsan\scoop\apps\python311\current\Lib\asyncio\base_events.py", line 654, in run_until_complete
  File "C:\Users\zhangsan\scoop\apps\python311\current\Lib\asyncio\base_events.py", line 654, in run_until_complete
  File "C:\Users\zhangsan\scoop\apps\python311\current\Lib\asyncio\base_events.py", line 654, in run_until_complete
  File "C:\Users\zhangsan\scoop\apps\python311\current\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
  File "C:\Users\zhangsan\scoop\apps\python311\current\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
mplete
    return future.result()
    return future.result()
           ^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^
  File "D:\Temp\f2\f2\cli\cli_commands.py", line 175, in run_app
  File "D:\Temp\f2\f2\cli\cli_commands.py", line 175, in run_app
    await app_module.main(kwargs)
  File "D:\Temp\f2\f2\apps\weibo\handler.py", line 347, in main
  File "D:\Temp\f2\f2\apps\weibo\handler.py", line 347, in main
    await mode_function_map[mode](WeiboHandler(kwargs))
    await mode_function_map[mode](WeiboHandler(kwargs))
  File "D:\Temp\f2\f2\apps\weibo\handler.py", line 283, in handle_user_weibo
  File "D:\Temp\f2\f2\apps\weibo\handler.py", line 283, in handle_user_weibo
    await self.downloader.create_download_tasks(
  File "D:\Temp\f2\f2\apps\weibo\dl.py", line 64, in create_download_tasks
    await self.handler_download(kwargs, weibo_data, user_path)
  File "D:\Temp\f2\f2\apps\weibo\dl.py", line 117, in handler_download
    await self.download_images()
  File "D:\Temp\f2\f2\apps\weibo\dl.py", line 160, in download_images
    for i, image_url in enumerate(self.weibo_data_dict.get("weibo_pic_ids", [])):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/user-attachments/assets/bf5ce6bb-04f2-4087-baf0-50d06e141ac3)
排查了一下发现是该微博不能在网页端查看

**Comment by Johnserf-Seed** [comment]
![image](https://github.com/user-attachments/assets/bc744216-09a8-46a1-9db5-cfa26d853190)
我用one模式测了不会触发错误
