### ISSUE TITLE
扫码获取cookie报错

### ISSUE THREAD

**Issue by QQ920924960** [Johnserf-Seed/f2#43]
<img width="1026" alt="image" src="https://github.com/Johnserf-Seed/f2/assets/7412045/21514f5b-e1c5-4f58-b1ba-6ef7fd2aed12">

**Comment by georgeJzzz** [comment]
`--auto-cookie` 报错
![image](https://github.com/Johnserf-Seed/f2/assets/42543889/255098a2-09df-4fea-80fd-6f88420182f2)

**Comment by Johnserf-Seed** [comment]
> `--auto-cookie` 报错
> ![image](https://github.com/Johnserf-Seed/f2/assets/42543889/255098a2-09df-4fea-80fd-6f88420182f2)
> 

问题说的很清楚了

**Comment by ljc222** [comment]
获取

> > `--auto-cookie` 报错
> > ![image](https://private-user-images.githubusercontent.com/42543889/308850504-255098a2-09df-4fea-80fd-6f88420182f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTU1MzQsIm5iZiI6MTcwOTIxNTIzNCwicGF0aCI6Ii80MjU0Mzg4OS8zMDg4NTA1MDQtMjU1MDk4YTItMDlkZi00ZmVhLTgwZmQtNmY4ODQyMDE4MmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE0MDAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3YTNlYmZkMzhiYWU5OWJiNDk1Mzg5YWFmZTRiNWMxYWM0NjU2ZDk3YmFiNmNkNDk2OGY1ZThkMzM0NjI2MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6TGIYOrH6f_O1q_Rqr3C4-5hxmBn6OzAACSnDMYvvfo)
> 
> 问题说的很清楚了

获取titok视频出错。
视频链接：
https://www.tiktok.com/@jordi.koalitic/video/7335823281393618208'
日志：
WARNING  第 1 次响应内容为空, 状态码: 200,
ERROR    无效响应类型。响应类型: <class 'NoneType'>
Traceback (most recent call last):
  File "D:\.pyenv\pyenv-win\versions\3.10.6\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\.pyenv\pyenv-win\versions\3.10.6\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\code\creator\venv\scripts\f2.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\code\creator\venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\code\creator\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\code\creator\venv\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\code\creator\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\code\creator\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\code\creator\venv\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\code\creator\venv\lib\site-packages\f2\apps\tiktok\cli.py", line 469, in tiktok
    ctx.invoke(set_cli_config, **kwargs)
  File "D:\code\creator\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\code\creator\venv\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\code\creator\venv\lib\site-packages\f2\cli\cli_commands.py", line 135, in set_cli_config
    asyncio.run(run_app(kwargs))
  File "D:\.pyenv\pyenv-win\versions\3.10.6\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\.pyenv\pyenv-win\versions\3.10.6\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\code\creator\venv\lib\site-packages\f2\cli\cli_commands.py", line 143, in run_app
    await app_module.main(kwargs)
  File "D:\code\creator\venv\lib\site-packages\f2\apps\tiktok\handler.py", line 665, in main
    await mode_function_map[mode](TiktokHandler(kwargs))
  File "D:\code\creator\venv\lib\site-packages\f2\apps\tiktok\handler.py", line 239, in handler_one_video
    await self.downloader.create_download_tasks(self.kwargs, aweme_data, user_path)
  File "D:\code\creator\venv\lib\site-packages\f2\apps\tiktok\dl.py", line 138, in create_download_tasks
    await self.handler_download(kwargs, aweme_data, user_path)
  File "D:\code\creator\venv\lib\site-packages\f2\apps\tiktok\dl.py", line 178, in handler_download
    format_file_name(
  File "D:\code\creator\venv\lib\site-packages\f2\apps\tiktok\utils.py", line 547, in format_file_name
    "desc": split_filename(aweme_data.get("desc", ""), os_limit),
  File "D:\code\creator\venv\lib\site-packages\f2\utils\utils.py", line 218, in split_filename
    chinese_length = sum(1 for char in text if "\u4e00" <= char <= "\u9fff") * 3
TypeError: 'NoneType' object is not iterable

**Comment by georgeJzzz** [comment]
好的 已经调试正常。 感谢

**Comment by qs-lll** [comment]
扫了 我直接锁定账号了！！！！！

**Comment by Johnserf-Seed** [comment]
> 扫了 我直接锁定账号了！！！！！

https://github.com/Johnserf-Seed/TikTokDownload/issues/680
扫码的接口更新了，而且一直都不推荐用扫码，因为很容易会风控
